import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '@/components/navbar'
import Footer from '@/components/footer'
import Providers from './providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Modern Clothes',
  description: 'Generated by @ayesha',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-myWhite` }>
        <div className='max-w-[90%] mx-auto'>
          <Providers>
          <Navbar/>
        {children}
        <Footer/>
          </Providers>
        </div>
        
        </body>
       
    </html>
  )
}
